### ISSUE TITLE
Procedure needed for MCCIP disaster recovery with no controller failures

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#364]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/task_recover_from_a_non_controller_failure_mcc_dr.html

### Page title

Recovering from a non-controller failure

### Summary

We only seem to document the process for MetroCluster FC systems recovering from a disaster with no controller failures. We should have another page with the steps for MetroCluster IP.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks for raising this. I'll verify and let you know when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks for raising this issue, we've updated the page so that it applies to FC and IP to address your feedback. Thanks again for helping us improve the documentation! 
https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/task_recover_from_a_non_controller_failure_mcc_dr.html#healing-the-configuration-in-a-metrocluster-configuration
