### ISSUE TITLE
Missing information about number of shelves and layout recommendations

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#369]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fb_new_install.html

### Page title

Installing FC-to-SAS bridges and SAS disk shelves

### Summary

We don't have any information on this page about how many shelves / drives are supported behind an ATTO. I also don't find this info on HWU or IMT.

Additionally it would be good if we could provide a recommendation that on the 7500N and 7600N bridges it is a good idea to split the stacks across all available SAS ports.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks for this suggestion. We'll review and let you know when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp we've made some initial updates to address this issue here: https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_install_fc_sas_bridges_shelves.html#supported-number-of-disks-and-shelves-on-fibrebridge-7600n-and-7500n-bridges

Further improvements to address this feedback is being tracked internally in ONTAPDOC-2293.
